source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SGYSwiftJSON_Tests', :exclusive => true do
  pod 'SGYSwiftJSON', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.2.0'
  pod 'SGYKVCSafeNSObject', '~> 1.0'
end
